# driver_interface.py
from typing import Protocol

class MotorDriverInterface(Protocol):
    def init(self) -> bool: ...
    def set_pwm(self, channel: int, duty: float) -> None: ...
    def set_direction(self, channel: int, forward: bool) -> None: ...
    def read_encoder(self, channel: int) -> int: ...
    def read_current(self, channel: int) -> float: ...
    def emergency_stop(self) -> None: ...
    def heartbeat(self) -> None: ...
    def shutdown(self) -> None: ...
